using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Swappable.UI;

[GenerateTypedNameReferences]
public sealed partial class SwappableWindow : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    public SwappableWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate()
}
